[package]
name = "todolist_cli"
version = "0.1.0"
authors = ["gugfug1 <gugfug1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
